CREATE TABLE `USUARIO` (
	`ID` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `NOMBRE` VARCHAR(20) NOT NULL,
    `APELLIDO` VARCHAR(20) NOT NULL,
    `EMAIL` VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
